# Generated by Django 4.1.7 on 2023-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateField(),
        ),
    ]
