# Generated by Django 4.1.7 on 2023-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpot', '0003_advertisement_status_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact_number',
            field=models.CharField(default='123 456 789', max_length=12),
        ),
    ]
