# Generated by Django 4.1.7 on 2023-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpot', '0004_advertisement_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='localization',
            field=models.CharField(default='brak', max_length=100),
            preserve_default=False,
        ),
    ]
